profile-name : beta

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:~/multi
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # or 'create' or 'update'
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true